# Generated by Django 4.1.1 on 2022-10-31 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesibleElement',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_text', models.TextField()),
                ('_pictogram', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accesibleelement')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accesibleelement')),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_accesible_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accesibleelement')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_due_date', models.DateField()),
                ('_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feedback')),
                ('_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accesibleelement')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenOrderDetail',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_quantity', models.IntegerField()),
                ('_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
                ('_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish')),
                ('_kitchen_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kitchenorder')),
            ],
        ),
        migrations.AddField(
            model_name='kitchenorder',
            name='_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task'),
        ),
        migrations.AddField(
            model_name='dish',
            name='_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dishtype'),
        ),
    ]
