# Generated by Django 4.1.1 on 2022-12-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibleMode',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextSize',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
