# Generated by Django 4.1.1 on 2022-10-31 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='_accesible_element',
            new_name='_feedback',
        ),
    ]