# Generated by Django 4.1.1 on 2022-12-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='_caps',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='_is_pass_pictogram',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='_pass_in_order',
            field=models.BooleanField(default=True),
        ),
    ]
