# Generated by Django 4.1.1 on 2022-12-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='_only_pictrograms',
            new_name='_only_pictograms',
        ),
    ]
