# Generated by Django 4.1.1 on 2022-12-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accessiblemode_textsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_password', models.TextField()),
                ('_caps', models.BooleanField()),
                ('_is_pass_pictogram', models.BooleanField()),
                ('_pass_in_order', models.BooleanField()),
                ('_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accessibleelement', unique=True)),
            ],
        ),
    ]
