# Generated by Django 4.1.1 on 2022-11-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename__accesible_element_feedback__feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccesibleElement',
            new_name='AccessibleElement',
        ),
    ]
