# Generated by Django 4.1.1 on 2022-12-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student__caps_alter_student__is_pass_pictogram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordPictogram',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_digit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accessibleelement')),
                ('_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
