# Generated by Django 4.1.1 on 2022-11-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task__status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accessibleelement')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_quantity', models.IntegerField(default=0)),
                ('_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.color')),
                ('_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accessibleelement')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTask',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='kitchenorder',
            name='_auto_calc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='_auto_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MaterialTaskDetail',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_quantity', models.IntegerField(default=1)),
                ('_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
                ('_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.material')),
                ('_material_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materialtask')),
            ],
        ),
        migrations.AddField(
            model_name='materialtask',
            name='_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task'),
        ),
    ]
