# Generated by Django 4.1.1 on 2022-12-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename__item_materialtype__name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='_feedback',
            new_name='_name',
        ),
    ]
