# Generated by Django 4.1.1 on 2022-11-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_accesibleelement_accessibleelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='_feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.feedback'),
        ),
    ]
