# Generated by Django 4.1.1 on 2022-11-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_color_material_materialtask_kitchenorder__auto_calc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtaskdetail',
            name='_classroom',
        ),
    ]
