# Generated by Django 4.1.1 on 2022-12-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterLaminatorTask',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_quantity', models.IntegerField(null=True)),
                ('_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
                ('_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.color')),
                ('_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
    ]
