# Generated by Django 4.1.1 on 2022-11-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task__feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.feedback'),
        ),
    ]
