# Generated by Django 4.1.1 on 2022-11-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_task__feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='_type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
