# Generated by Django 4.1.1 on 2022-12-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_printerlaminatortask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_username', models.CharField(max_length=32, unique=True)),
                ('_password', models.TextField()),
                ('_admin', models.BooleanField(default=False)),
                ('_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accessibleelement')),
            ],
        ),
    ]
