# Generated by Django 4.1.1 on 2022-12-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
                ('_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
    ]
