# Generated by Django 4.1.1 on 2022-12-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teaches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teaches',
            new_name='Teach',
        ),
    ]
