# Generated by Django 4.1.1 on 2022-12-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_teaches_teach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='_admin',
            new_name='_is_admin',
        ),
    ]
