# Generated by Django 4.1.1 on 2022-12-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename__admin_teacher__is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.color'),
        ),
    ]
