# Generated by Django 4.1.1 on 2022-12-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_material__color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='_name',
            field=models.TextField(unique=True),
        ),
    ]
