# * http://localhost:8000/api/accesible_element

GET http://localhost:8000/api/accesible_element

###

POST http://localhost:8000/api/accesible_element

{
    "_text" : "Clase E",
    "_pictogram": "https://static.vecteezy.com/system/resources/previews/000/401/729/original/vector-capital-letter-a-vintage-typography-style.jpg"
}

### * http://localhost:8000/api/accesible_element/<_id>

GET http://localhost:8000/api/accesible_element/1

###

PUT http://localhost:8000/api/accesible_element/16

{
    "_text" : "Clase E",
    "_pictogram" : "https://static.vecteezy.com/system/resources/previews/000/401/729/original/vector-capital-letter-a-vintage-typography-style.jpg"
}


###

DELETE http://localhost:8000/api/accesible_element/13