# * http://localhost:8000/api/accesible_element

GET http://0.0.0.0:8000/api/accessible_element

###

POST http://localhost:8000/api/accessible_element

{
    "_text": "Antonio García",
    "_pictogram": "https://api.arasaac.org/api/pictograms/8672?resolution=500&download=false",
    "_alt": "Imagen que identifica al profesor Antonio García"
}

### * http://localhost:8000/api/accesible_element/<_id>

GET http://localhost:8000/api/accessible_element/2

###

PUT http://localhost:8000/api/accessible_element/2

{
    "_id" : "Fruta",
    "_pictogram" : "https://api.arasaac.org/api/pictograms/4653?download=false"
}

###

DELETE http://localhost:8000/api/accessible_element/13
### * ARASAAC

GET https://api.arasaac.org/api/pictograms/es/bestSearch/coche

### * IMÁGENES

GET http://localhost:8000/api/image