# * http://localhost:8000/api/classroom

GET http://localhost:8000/api/classroom

###

POST http://localhost:8000/api/classroom

{
    "_class_code": "1"
}

###

GET http://localhost:8000/api/classroom/1

###

PUT http://localhost:8000/api/classroom/1

{
    "_class_code" : "1"
}

###

DELETE http://localhost:8000/api/classroom/1