# * http://localhost:8000/api/classroom

GET http://localhost:8000/api/classroom

###

POST http://localhost:8000/api/classroom

{
    "_name": "7"
}

###

GET http://localhost:8000/api/classroom/1

###

PUT http://localhost:8000/api/classroom/1

{
    "_name" : "1"
}

###

DELETE http://localhost:8000/api/classroom/1