# * http://localhost:8000/api/dish

GET http://localhost:8000/api/dish

###

POST http://localhost:8000/api/dish

{
    "_name" : "6",
    "_type": "MENU"
}

### * http://localhost:8000/api/dish/<_id>

GET http://localhost:8000/api/dish/1

###

PUT http://localhost:8000/api/dish/1

{
    "_name" : "2"
}


###

DELETE http://localhost:8000/api/dish/1