# * http://localhost:8000/api/kitchen_order_detail

GET http://localhost:8000/api/kitchen_order_detail

###
GET http://localhost:8000/api/kitchen_order_detail/7/1

###

POST http://localhost:8000/api/kitchen_order_detail

{
    "_quantity" : "0",
    "_classroom" : "1",
    "_dish" : "3",
    "_kitchen_order" : "1"
}

### * http://localhost:8000/api/kitchen_order_detail/<_id>

PUT  http://localhost:8000/api/kitchen_order_detail/5

{
    "_quantity": 1
}

###

GET http://localhost:8000/api/kitchen_order_detail/1

###

DELETE http://localhost:8000/api/kitchen_order_detail/1