GET http://localhost:8000/api/printer_laminator_task

###

POST http://localhost:8000/api/printer_laminator_task

{
    "_classroom": "1",
    "_task": "11"
}

###

GET http://localhost:8000/api/task/12

###

PUT http://localhost:8000/api/printer_laminator_task/1

{
    "_classroom": "8"
}


###

DELETE http://localhost:8000/api/task/11