# * http://localhost:8000/api/task

GET http://localhost:8000/api/task

###

POST http://localhost:8000/api/task

{
    "_name" : "1",
    "_feedback": "1",
    "_due_date": "2022-11-22",
    "_type": "MATERIAL",
    "_status": "True",
    "_auto_feedback": "True"


}

### * http://localhost:8000/api/task/<_id>

GET http://localhost:8000/api/task/2

###

PUT http://localhost:8000/api/task/1

{
    "_name" : "16",
    "_due_date": "2015-03-25"
}


###

DELETE http://localhost:8000/api/task/1